export const emailBlastRecipients = [
  { name: "Shorouk Ahmed Said Abdelaty Saleh Elsharkawy", email: "shorouk@oiaproperties.com", department: "Listing" },
  { name: "Shumaila Umer Umer Ishaq", email: "shumaila@oiaproperties.com", department: "Listing" },
  { name: "Nehal Ahmed Hammam Ghalab", email: "nehal@oiaproperties.com", department: "Listing" },
  { name: "Hadeer Ahmed Abdelfattah Shaaban", email: "hadeer@oiaproperties.com", department: "Listing" },
  { name: "Sahar Traad Mhho", email: "sahar@oiaproperties.com", department: "Listing" },
  { name: "Esra Ibrahim Osman Abdelgader", email: "esraa.ibrahim@oiaproperties.com", department: "Listing" },
  { name: "Esra Elmamoun Ahmed Elsiddig", email: "esra.elmamoun@oiaproperties.com", department: "Listing" },
  { name: "Mahmoud Mohsen Mahmoud Elhanafi", email: "m.mohsen@oiaproperties.com", department: "Listing" },
  { name: "Ammar Alaa Abdelsalam Hekal", email: "ammar.h@oiaproperties.com", department: "Listing" },
  { name: "Samih Hakim Rezkalla Ghaly", email: "samih.g@oiaproperties.com", department: "Listing" },
  { name: "Louay Wahid Alhammady", email: "l.alhammady@oiaproperties.com", department: "Listing" },
  { name: "Assem Samir Hamdi Abdelgawwad Ali", email: "assem.a@oiaproperties.com", department: "Listing" },
  { name: "Mohamed Ibrahim Mohamed Fawzy Mohamed Elhatab", email: "m.ibrahim@oiaproperties.com", department: "Listing" },
  { name: "Saad Mohamed Mohamed Awad", email: "saad.a@oiaproperties.com", department: "Listing" },
  { name: "Dena Khaled Mamdouh Hussein Elfar", email: "dena@oiaproperties.com", department: "Listing" },
  { name: "Mario Fayad", email: "mario.f@oiaproperties.com", department: "Listing" },
  { name: "Mustafa Amir Hassan Khalafalla", email: "mustafa.amir@oiaproperties.com", department: "Listing" },
  { name: "Dany Feras Alnabwani", email: "dany@oiaproperties.com", department: "Listing" },
  { name: "Stephanie Shane Marie Ortega Lozada", email: "stephanie@oiaproperties.com", department: "Listing" },
  { name: "Jakhongir Nurilla Ugli Bukhorov", email: "jakhongir.b@oiaproperties.com", department: "Listing" },
  { name: "Ahmad Mohd Fuad Ata Nasereddin", email: "a.naser@oiaproperties.com", department: "Sales" },
  { name: "Nowar Bader Aldeen Sammoni", email: "nawar@oiaproperties.com", department: "Sales" },
  { name: "Rajaa Balmane", email: "rajaa@oiaproperties.com", department: "Sales" },
  { name: "Qusai Saleh Alsaidahmad", email: "qusai@oiaproperties.com", department: "Sales" },
  { name: "Anas Essam Murad", email: "anas@oiaproperties.com", department: "Sales" },
  { name: "Obada Mazen Omran", email: "obada@oiaproperties.com", department: "Sales" },
  { name: "Ghanem Ali Ghanem", email: "ghanem@oiaproperties.com", department: "Sales" },
  { name: "Dina Ehab Ahmed Sayed", email: "dina@oiaproperties.com", department: "Sales" },
  { name: "Lina Benchaouche", email: "lyna@oiaproperties.com", department: "Sales" },
  { name: "Fatma R S Abueida", email: "fatima@oiaproperties.com", department: "Sales" },
  { name: "Ashraf Ali Ghalyouni", email: "ashraf@oiaproperties.com", department: "Sales" },
  { name: "Abouobaida Elsayed Moussa Ali", email: "abuoubaida@oiaproperties.com", department: "Sales" },
  { name: "Hajar Benassou", email: "hajar@oiaproperties.com", department: "Sales" },
  { name: "Noha Ahmed Mohamed Abdelhalim", email: "noha@oiaproperties.com", department: "Sales" },
  { name: "Qamar Magd Aldeen Alhusen", email: "qamar@oiaproperties.com", department: "Sales" },
  { name: "Ahmed Ahmed Hanafy Bakr", email: "a.hanafy@oiaproperties.com", department: "Sales" },
  { name: "Sulafa Elsadig Holy Ahmed", email: "sulafa@oiaproperties.com", department: "Sales" },
  { name: "Waseem Wassef Mahmoud", email: "waseem@oiaproperties.com", department: "Sales" },
  { name: "Yasmeen Abdlrhman Hasan", email: "yasmina@oiaproperties.com", department: "Sales" },
  { name: "Pasant Yousry Mohamed Onsy", email: "pasant@oiaproperties.com", department: "Sales" },
  { name: "Oday Hamad Salloum", email: "o.salloum@oiaproperties.com", department: "Sales" },
  { name: "Anas Mohamed Adam Ali", email: "a.adam@oiaproperties.com", department: "Sales" },
  { name: "Ali Haitham Kassem", email: "a.kassem@oiaproperties.com", department: "Sales" },
  { name: "Sahar Elsadig Holy Ahmed", email: "sahar.h@oiaproperties.com", department: "Sales" },
  { name: "Zeyad Elhusseini Abdelaal Desouky Elhout", email: "zeyad@oiaproperties.com", department: "Sales" },
  { name: "Mostafa Adel Ibrahim Sayed", email: "mustafa.a@oiaproperties.com", department: "Sales" },
  { name: "Abdelsalam Zakaria Abdelsalam Mohamed Khater", email: "khater@oiaproperties.com", department: "Sales" },
  { name: "Fadi Hesham Mammar", email: "fadi@oiaproperties.com", department: "Sales" },
  { name: "Eslam Ahmad Baiomy Moussa", email: "eslam@oiaproperties.com", department: "Sales" },
  { name: "Ahmed Saied El-Daghash", email: "a.eldaghash@oiaproperties.com", department: "Sales" },
  { name: "Mohamed Tarek Saad", email: "m.tarek@oiaproperties.com", department: "Sales" },
  { name: "Amer Emasha", email: "emasha@oiaproperties.com", department: "Sales" },
  { name: "Razan Ahmad Aljumaa", email: "razan.a@oiaproperties.com", department: "Sales" },
  { name: "Marwan Khalil Abdelhamid Mohamed Sobh", email: "marwan@oiaproperties.com", department: "Sales" },
  { name: "Ahmed Gamal", email: "a.gamal@oiaproperties.com", department: "Sales" },
  { name: "Elsayed Abouhashem", email: "sayed@oiaproperties.com", department: "Sales" },
  { name: "Ebraheem Abdallatiff Ebraheem Abdallatiff", email: "ebraheem@oiaproperties.com", department: "Sales" },
  { name: "Aya Khaled Alkayem", email: "aya.alkayem@oiaproperties.com", department: "Sales" },
  { name: "Mohamed Fathy Mohamed Ahmed Elmisany", email: "mohamed.fathy@oiaproperties.com", department: "Sales" },
  { name: "Mohamed Aly Mohamed Aly Abdellatif", email: "m.abdellatif@oiaproperties.com", department: "Sales" },
  { name: "Mhd Laith Mohammad Thaljeh", email: "laith@oiaproperties.com", department: "Sales" },
  { name: "Hasan Khordouk", email: "h.khourdok@oiaproperties.com", department: "Sales" },
  { name: "Ahmed Yaser Momtasil Ousman", email: "ahmed.yaser@oiaproperties.com", department: "Sales" },
  { name: "Mais Zaizafoon", email: "mais.z@oiaproperties.com", department: "Sales" },
  { name: "Adham Shawki Maati Maati Eltoutoungi", email: "adham.a@oiaproperties.com", department: "Sales" },
  { name: "Mahfood Oraij", email: "mahfood.o@oiaproperties.com", department: "Sales" },
  { name: "Zein Alabedin Mouhsen Ali", email: "zein.a@oiaproperties.com", department: "Sales" },
  { name: "Moayad Shehadeh Mahmoud Helaly", email: "moayad.h@oiaproperties.com", department: "Sales" },
  { name: "Mahmoud Mohamed Mashhot Ibrahim", email: "mahmoud.i@oiaproperties.com", department: "Sales" },
  { name: "Mahmoud Ezzat Obeid", email: "mahmoudezzat@oiaproperties.com", department: "Sales" },
  { name: "Khaled Mohammad Abdel Majid Al Najjar", email: "khaled.n@oiaproperties.com", department: "Sales" },
  { name: "Ahmed Ali Abbas Abdelhadi", email: "ahmedali.a@oiaproperties.com", department: "Sales" },
  { name: "Rabee Bassam Alendary", email: "rabee@oiaproperties.com", department: "Sales" },
  { name: "Mohamed Abdelhakim Gad Ibrahim Saafan", email: "hakim@oiaproperties.com", department: "Sales" },
  { name: "Mahmoud Ahmed Mohamed Mohamed", email: "mahmoudahmed@oiaproperties.com", department: "Sales" },
  { name: "Mahmoud Ibrahim Mahmoud Mohamed Naga", email: "mahmoudibrahim@oiaproperties.com", department: "Sales" },
  { name: "Alisia Lida Grigoriou", email: "alisia@oiaproperties.com", department: "Sales" },
  { name: "Noureldien Mahmoud Abdelazeem Hafez", email: "noureldien@oiaproperties.com", department: "Sales" },
  { name: "Ahmad Hamdy Mohamed Abdelaal Gad", email: "a.hamdy@oiaproperties.com", department: "Sales" },
  { name: "Cristina Alejandra Condor Perez", email: "alejandra@oiaproperties.com", department: "Sales" },
  { name: "Imane Elkarni", email: "imane.e@oiaproperties.com", department: "Sales" },
  { name: "Moataz Mohsen Sadek Elmakawy", email: "m.makawy@oiaproperties.com", department: "Sales" },
  { name: "Sameh Mahmoud Ahmed Soliman", email: "sameh.s@oiaproperties.com", department: "Sales" },
  { name: "Ramez Ashraf Ramzy Shehata Elmasry", email: "ramez@oiaproperties.com", department: "Sales" },
  { name: "Noor Magdy Moustafa Mahfouz", email: "noor.m@oiaproperties.com", department: "Sales" },
  { name: "Mohamed Moustafa Mahmoud", email: "m.moustafa@oiaproperties.com", department: "Sales" },
  { name: "Layal Rami Hnaidi", email: "layal@oiaproperties.com", department: "Sales" },
  { name: "Mohamed Salah Abdelhamid Salama", email: "mohamed.salah@oiaproperties.com", department: "Sales" },
  { name: "Tayseer Kamal Alkazahli", email: "tayseer@oiaproperties.com", department: "Sales" },
  { name: "Elsayed Ibrahim Sayed Aboelgheit", email: "elsayed.ibrahim@oiaproperties.com", department: "Sales" },
  { name: "Jhonatan Legarda Perez", email: "jhonatan@oiaproperties.com", department: "Sales" },
  { name: "Siba Mohamad Tayar", email: "siba.m@oiaproperties.com", department: "Sales" },
  { name: "Ahmed Mohamed Ali Khalil Abdelkhalik", email: "a.abdelkhalik@oiaproperties.com", department: "Sales" },
  { name: "Wiam Lakbiri", email: "wiam.l@oiaproperties.com", department: "Sales" },
  { name: "Iyas Ziad Layous", email: "iyas.l@oiaproperties.com", department: "Sales" },
  { name: "Ali Fesl Mohamad", email: "ali.fesl@oiaprroperties.com", department: "Sales" },
  { name: "Nahar Fahed Alma", email: "nahar@oiaproperties.com", department: "Sales" },
  { name: "Monica Ashraf Fayez Georgy Abdelmalak", email: "monica.a@oiaproperties.com", department: "Sales" },
  { name: "Osama Ghalyouni", email: "osama.g@oiaproperties.com", department: "Sales" },
  { name: "Mostafa Adel Saber Shafie", email: "mostafa.adel@oiaproperties.com", department: "Sales" },
  { name: "Khaled Adil Saber Shafie", email: "khaled.adil@oiaproperties.com", department: "Sales" },
  { name: "Samar Ahmed Samy Abdelkerim Ahmed Eldahar", email: "samar.samy@oiaproperties.com", department: "Sales" },
  { name: "Mohamed Maher Mahmoud Eladl", email: "mohamed.maher@oiaproperties.com", department: "Sales" },
  { name: "Emad Mahmoud Ibrahim Mohamed Ibrahim", email: "emad.mahmoud@oiaproperties.com", department: "Sales" },
  { name: "Yasmin Mohamed Ibrahim Elsayed Elsaghir", email: "yasmin.e@oiaproperties.com", department: "Sales" },
  { name: "Abdallah Mohamad Ayyed Al Huqaish", email: "a.huqaish@oiaproperties.com", department: "Sales" },
  { name: "Radwan Jadallah Alsayed", email: "radwan.a@oiaproperties.com", department: "Sales" },
  { name: "Danial Ahsan Maklad", email: "danial.m@oiaproperties.com", department: "Sales" },
  { name: "Rana Kefah Awwad Bani Hani", email: "rana.kefah@oiaproperties.com", department: "Sales" },
  { name: "Mina Tahmoures Saghati", email: "mina.s@oiaproperties.com", department: "Sales" },
  { name: "Nesma Elsayed Abdelfatah Elsayed Farag", email: "nesma@oiaproperties.com", department: "Sales" },
  { name: "Dounia Wahab", email: "dounia.wahab@oiaproperties.com", department: "Sales" },
  { name: "Loay Maaeh Alhadi", email: "loay.alhadi@oiaproperties.com", department: "Sales" },
  { name: "Mohamed Mohamed Hussein Ali Kabil", email: "mohamed.k@oiaproperties.com", department: "Sales" },
  { name: "Bahaa Emad Ghanem", email: "bahaa.g@oiaproperties.com", department: "Sales" },
  { name: "Mina Mounir Zaky Faltas", email: "mina.mounir@oiaproperties.com", department: "Sales" },
  { name: "Amira Mohamed Mahmoud Ahmed Badellah", email: "amira.b@oiaproperties.com", department: "Sales" },
]
