<?php

/**
 * Dictionaries for Listing Voice Search (Phase 1 foundation).
 * Arabic / English / mixed transcripts are mapped to internal English DB values.
 */
return [

    'property_types' => [
        // Arabic
        'شقة' => 'Apartment',
        'شقق' => 'Apartment',
        'فيلا' => 'Villa',
        'فلل' => 'Villa',
        'تاون هاوس' => 'Townhouse',
        'تاونهاوس' => 'Townhouse',
        'بنتهاوس' => 'Penthouse',
        'دوبلكس' => 'Duplex',
        'استوديو' => 'Studio',
        'أرض' => 'Plot',
        'ارض' => 'Plot',
        'مكتب' => 'Office',
        'محل' => 'Shop',
        // English + synonyms
        'apartment' => 'Apartment',
        'apartments' => 'Apartment',
        'apt' => 'Apartment',
        'flat' => 'Apartment',
        'villa' => 'Villa',
        'villas' => 'Villa',
        'townhouse' => 'Townhouse',
        'townhouses' => 'Townhouse',
        'town house' => 'Townhouse',
        'penthouse' => 'Penthouse',
        'duplex' => 'Duplex',
        'studio' => 'Studio',
        'plot' => 'Plot',
        'land' => 'Plot',
        'office' => 'Office',
        'shop' => 'Shop',
    ],

    'bedrooms' => [
        // Arabic
        'استوديو' => 0,
        'غرفة' => 1,
        'غرفه' => 1,
        'غرفة واحدة' => 1,
        'غرفه واحده' => 1,
        'غرفتين' => 2,
        'غرفتين نوم' => 2,
        'ثلاث غرف' => 3,
        'ثلاث غرف نوم' => 3,
        'ثلاثة غرف' => 3,
        'اربع غرف' => 4,
        'أربع غرف' => 4,
        'خمس غرف' => 5,
        'ست غرف' => 6,
        // English synonyms / abbreviations
        'studio' => 0,
        '1 bedroom' => 1,
        '1 bed' => 1,
        '1 br' => 1,
        'one bedroom' => 1,
        'one bed' => 1,
        '2 bedroom' => 2,
        '2 bedrooms' => 2,
        '2 bed' => 2,
        '2 beds' => 2,
        '2 br' => 2,
        'two bedroom' => 2,
        'two bedrooms' => 2,
        'two bed' => 2,
        'three bedroom' => 3,
        'three bedrooms' => 3,
        '3 bedroom' => 3,
        '3 bedrooms' => 3,
        '3 bed' => 3,
        '3 br' => 3,
        'four bedroom' => 4,
        '4 bedroom' => 4,
        '4 bedrooms' => 4,
        '4 br' => 4,
        'five bedroom' => 5,
        '5 bedroom' => 5,
        '5 bedrooms' => 5,
        '5 br' => 5,
        'six bedroom' => 6,
        '6 bedroom' => 6,
        '6 bedrooms' => 6,
        '6 br' => 6,
    ],

    'bathrooms' => [
        'حمام' => 1,
        'حمامين' => 2,
        'ثلاث حمامات' => 3,
        '1 bathroom' => 1,
        '1 bath' => 1,
        'one bathroom' => 1,
        '2 bathroom' => 2,
        '2 bathrooms' => 2,
        '2 bath' => 2,
        'two bathroom' => 2,
        'two bathrooms' => 2,
        '3 bathroom' => 3,
        '3 bathrooms' => 3,
        'three bathroom' => 3,
        'three bathrooms' => 3,
    ],

    'purpose' => [
        'بيع' => 'sale',
        'للبيع' => 'sale',
        'شراء' => 'sale',
        'ايجار' => 'rent',
        'إيجار' => 'rent',
        'للايجار' => 'rent',
        'للإيجار' => 'rent',
        'ايجاار' => 'rent',
        'sale' => 'sale',
        'buy' => 'sale',
        'for sale' => 'sale',
        'rent' => 'rent',
        'for rent' => 'rent',
        'rental' => 'rent',
    ],

    'areas' => [
        // Arabic → canonical English DB name
        'جزيرة الريم' => 'Reem Island',
        'الريم' => 'Reem Island',
        'ريم' => 'Reem Island',
        'جزيرة ياس' => 'Yas Island',
        'ياس' => 'Yas Island',
        'ياس آيلاند' => 'Yas Island',
        'جزيرة السعديات' => 'Saadiyat Island',
        'السعديات' => 'Saadiyat Island',
        'الخليج الغربي' => 'Al Khalidiyah',
        'الخالدية' => 'Al Khalidiyah',
        'المارینا' => 'Al Marina',
        'المارينا' => 'Al Marina',
        'البطين' => 'Al Bateen',
        'المصفح' => 'Musaffah',
        'مدينة محمد بن زايد' => 'Mohamed Bin Zayed City',
        'شارع المطار' => 'Airport Road',
        // English aliases
        'reem island' => 'Reem Island',
        'al reem island' => 'Reem Island',
        'reem' => 'Reem Island',
        'yas island' => 'Yas Island',
        'yas' => 'Yas Island',
        'saadiyat island' => 'Saadiyat Island',
        'saadiyat' => 'Saadiyat Island',
        'al khalidiyah' => 'Al Khalidiyah',
        'khalidiyah' => 'Al Khalidiyah',
        'al marina' => 'Al Marina',
        'marina' => 'Al Marina',
        'al bateen' => 'Al Bateen',
        'bateen' => 'Al Bateen',
        'musaffah' => 'Musaffah',
        'mussa fah' => 'Musaffah',
        'mbz' => 'Mohamed Bin Zayed City',
        'mohamed bin zayed city' => 'Mohamed Bin Zayed City',
        'airport road' => 'Airport Road',
    ],

    /**
     * Arabic / English price phrases → AED amount helpers.
     * Parsed dynamically in VoiceSearchService; kept here for reference synonyms.
     */
    'price_words' => [
        'مليون' => 1_000_000,
        'ملیون' => 1_000_000,
        'million' => 1_000_000,
        'm' => 1_000_000,
        'الف' => 1_000,
        'ألف' => 1_000,
        'thousand' => 1_000,
        'k' => 1_000,
        'ونص' => 0.5,
        'ونصف' => 0.5,
        'نصف' => 0.5,
        'half' => 0.5,
    ],

    'noise_words' => [
        'عايز', 'عايزة', 'عاوز', 'عاوزة', 'ابي', 'أبي', 'ابغى', 'أبغى',
        'اريد', 'أريد', 'بدي', 'في', 'على', 'بـ', 'ب', 'عن', 'من',
        'i', 'need', 'want', 'looking', 'for', 'a', 'an', 'the', 'in', 'at',
        'with', 'under', 'below', 'above', 'over', 'around', 'please',
    ],
];
